package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"

	"github.com/davidalecrim/red-airlines/internal/graph/generated"
	"github.com/davidalecrim/red-airlines/internal/graph/model"
)

// Flight is the resolver for the flight field.
func (r *bookingResolver) Flight(ctx context.Context, obj *model.Booking) (*model.Flight, error) {
	result, err := r.Loaders.FlightLoader.Load(ctx, obj.FlightID)()
	if err != nil {
		return nil, err
	}
	return result, nil
}

// Fare is the resolver for the fare field.
func (r *bookingResolver) Fare(ctx context.Context, obj *model.Booking) (*model.Fare, error) {
	result, err := r.Loaders.FareLoader.Load(ctx, obj.FareID)()
	if err != nil {
		return nil, err
	}
	return result, nil
}

// Flight is the resolver for the flight field.
func (r *fareResolver) Flight(ctx context.Context, obj *model.Fare) (*model.Flight, error) {
	result, err := r.Loaders.FlightLoader.Load(ctx, obj.FlightID)()
	if err != nil {
		return nil, err
	}
	return result, nil
}

// Bookings is the resolver for the bookings field.
func (r *fareResolver) Bookings(ctx context.Context, obj *model.Fare) ([]*model.Booking, error) {
	result, err := r.Loaders.BookingsByFareLoader.Load(ctx, obj.ID)()
	if err != nil {
		return nil, err
	}
	return result, nil
}

// Fares is the resolver for the fares field.
func (r *flightResolver) Fares(ctx context.Context, obj *model.Flight) ([]*model.Fare, error) {
	result, err := r.Loaders.FaresByFlightLoader.Load(ctx, obj.ID)()
	if err != nil {
		return nil, err
	}
	return result, nil
}

// Bookings is the resolver for the bookings field.
func (r *flightResolver) Bookings(ctx context.Context, obj *model.Flight) ([]*model.Booking, error) {
	result, err := r.Loaders.BookingsByFlightLoader.Load(ctx, obj.ID)()
	if err != nil {
		return nil, err
	}
	return result, nil
}

// Flights is the resolver for the flights field.
func (r *queryResolver) Flights(ctx context.Context, origin *string, destination *string, limit *int) ([]*model.Flight, error) {
	query := "SELECT * FROM flights WHERE 1=1"
	args := []any{}

	if origin != nil {
		query += " AND origin = ?"
		args = append(args, *origin)
	}
	if destination != nil {
		query += " AND destination = ?"
		args = append(args, *destination)
	}

	query += " ORDER BY departure_time"

	if limit != nil && *limit > 0 {
		query += " LIMIT ?"
		args = append(args, *limit)
	}

	query = r.DB.Rebind(query)

	var flights []*model.Flight
	if err := r.DB.SelectContext(ctx, &flights, query, args...); err != nil {
		return nil, err
	}

	return flights, nil
}

// Flight is the resolver for the flight field.
func (r *queryResolver) Flight(ctx context.Context, id string) (*model.Flight, error) {
	var flight model.Flight
	if err := r.DB.GetContext(ctx, &flight, "SELECT * FROM flights WHERE id = $1", id); err != nil {
		return nil, err
	}
	return &flight, nil
}

// Booking is the resolver for the booking field.
func (r *queryResolver) Booking(ctx context.Context, bookingReference string) (*model.Booking, error) {
	var booking model.Booking
	if err := r.DB.GetContext(ctx, &booking, "SELECT * FROM bookings WHERE booking_reference = $1", bookingReference); err != nil {
		return nil, err
	}
	return &booking, nil
}

// Bookings is the resolver for the bookings field.
func (r *queryResolver) Bookings(ctx context.Context, passengerEmail *string, limit *int) ([]*model.Booking, error) {
	query := "SELECT * FROM bookings WHERE 1=1"
	args := []any{}

	if passengerEmail != nil {
		query += " AND passenger_email = ?"
		args = append(args, *passengerEmail)
	}

	query += " ORDER BY booked_at DESC"

	if limit != nil && *limit > 0 {
		query += " LIMIT ?"
		args = append(args, *limit)
	}

	query = r.DB.Rebind(query)

	var bookings []*model.Booking
	if err := r.DB.SelectContext(ctx, &bookings, query, args...); err != nil {
		return nil, err
	}

	return bookings, nil
}

// Airports is the resolver for the airports field.
func (r *queryResolver) Airports(ctx context.Context) ([]string, error) {
	query := `
		SELECT DISTINCT airport
		FROM (
			SELECT origin AS airport FROM flights
			UNION
			SELECT destination AS airport FROM flights
		) AS all_airports
		ORDER BY airport
	`

	var airports []string
	if err := r.DB.SelectContext(ctx, &airports, query); err != nil {
		return nil, err
	}

	return airports, nil
}

// Booking returns generated.BookingResolver implementation.
func (r *Resolver) Booking() generated.BookingResolver { return &bookingResolver{r} }

// Fare returns generated.FareResolver implementation.
func (r *Resolver) Fare() generated.FareResolver { return &fareResolver{r} }

// Flight returns generated.FlightResolver implementation.
func (r *Resolver) Flight() generated.FlightResolver { return &flightResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type (
	bookingResolver struct{ *Resolver }
	fareResolver    struct{ *Resolver }
	flightResolver  struct{ *Resolver }
	queryResolver   struct{ *Resolver }
)
