.PHONY: install dev build preview clean lint format codegen

install:
	npm install

run:
	npm run dev

build:
	npm run build

preview:
	npm run preview

clean:
	rm -rf node_modules dist

lint:
	npm run lint

format:
	npm run format

codegen:
	npm run codegen
